name: Run automated tests
run-name: Tests are being run after ${{ github.actor }}'s push
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64 q
      - name: Execute tests
        run: mvn verify
      - run: echo "Job finished with status ${{ job.status }}."