name: Run automated tests
run-name: ${{ github.actor }} is running tests after push
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Execute tests
        run: mvn verify
      - run: echo "This job's status is ${{ job.status }}."